Account "root" in "raw-options"
ofek/hatch-vcs pull request #17
Opened 2022-12-03 10:13 UTC by quarckster

Fixes #16.

2022-12-03 11:14 UTC, RonnyPfannschmidt commented on hatch_vcs/version_source.py
> -        config['root'] = self.root
I believe this fix is incomplete as root for hatch and setuptools_scm are distinct ideas

2022-12-03 17:05 UTC, ofek requested changes

2022-12-03 17:05 UTC, ofek commented on hatch_vcs/version_source.py
> +        config['root'] = config.get('root', self.root)
```suggestion
        config.setdefault('root', self.root)
```

2022-12-07 01:35 UTC, ofek commented on tests/test_version_config.py
> +        assert version_source.setuptools_scm_config["root"] == ".."
```suggestion
        assert version_source.setuptools_scm_config['root'] == '..'
```

2022-12-07 01:40 UTC, ofek commented on hatch_vcs/version_source.py
> +
```suggestion

```

2022-12-07 01:54 UTC, ofek commented on hatch_vcs/version_source.py
> +    @property
```suggestion

    @property
```

2022-12-07 02:41 UTC, merged